---
# brings up the dependencies
version: '2'
services:
  presto:
    build: .
    links:
      - postgis
    depends_on:
      - postgis
    ports:
      - "8080:8080"
  
  postgis:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"
